list p=16F887

_CONFIG1    EQU	H'2007'
_CONFIG2    EQU H'2008'
STATUS	    EQU H'0003'
TRISA	    EQU H'0085'
TRISB	    EQU H'0086'
TRISC	    EQU H'0087'
ANSEL	    EQU H'0188'
ANSELH	    EQU H'0189'
PORTA	    EQU H'0005'	    ;CARGAR VALOR DE INICIO
PORTB	    EQU H'0006'	    ;SALIDA UNIDADES Y DECENAS
PORTC	    EQU H'0007'	    ;SALIDA CENTENAS
PORTD	    EQU H'0008'	    
RA0	    EQU H'0000'
RA1	    EQU H'0001'	    ;REINICIO
RP0	    EQU H'0005'
RP1	    EQU H'0006'
OSCCON	    EQU H'008F'

;CONFIGURACION DE BITS
__CONFIG _CONFIG1, 0XE3F4
__CONFIG _CONFIG2, 0XFEFF
	    
;DEFINICION DE VARIABLES
CBLOCK 0X20
	C1	;0X20
	CONT2	;0X21
	CONTX
	CONTY
	UNI	;0X24 REGISTRO DE UNIDADES
	DEC	
	CEN
	X	;REGISTRO PARA CONTAR EL EL CONVERSOR
	CONT1
	A	;REGISTRO PARA LAS DECENAS EN SUBRUTINA VER
	MIN	;REGISTRO PARA CONTAR EL MINUTO DE LA SECUENCIA
	RST	;RESET
ENDC
	
ORG .0
  CALL	OSC_CONF
  CALL	PORT_CONF
LOOP:  
  INCF	CONT1
  CALL	CONVERSOR
  CALL	VER
  CALL	RETARDO
  BTFSS	PORTD,0	    ;TESTEO EL BIT 0 EN D Y SI ESTÁ ENCENDIDO SALTA LA SIG INSTRUCCION
  GOTO	$+4	    ;REGRESA AL CONVERSOR
  MOVFW	PORTA	    ;ASIGNO EL VR DE CONT1 AL PUERTO A
  MOVWF	CONT1	    
  GOTO	$-7	    ;REGRESA AL CONVERSOR
  MOVLW	0XFF
  XORWF	CONT1,0
  BTFSC	STATUS,2
  CALL	SECUENCIA
  GOTO	LOOP
  
  #INCLUDE  "CONFIGURACIONES.INC"
  #INCLUDE  "CONVERSOR.INC"
  #INCLUDE  "SECUENCIA.INC"
  #INCLUDE  "P16F887.INC"
  #INCLUDE  "RETARDO.INC"
  #INCLUDE  "VER.INC"
  
END